insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Noel MacCulloch', '8699022625', 'nmacculloch0@narod.ru', 'Staff', 'iNt6aLjM9vF8bWd', 'pyezvzErnoik');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Daron Wither', '7931168734', 'dwither1@sciencedaily.com', 'Staff', 'rKf2yGzVhP5sN7c', 'HaM2YZi6PPiy');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Gaven Jowsey', '2717553440', 'gjowsey2@soup.io', 'Staff', 'rJc5nUvDpL6gKxh', 'yPKoF7F8w');
insert into login (fullname, phone_number, email_address, account_type, password) values ('Flinn Jiricka', '8341076722', 'fjiricka3@reference.com', 'Merchant', 'lstIwtK');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Constantina Phayre', '4466919766', 'cphayre4@whitehouse.gov', 'Logistics', 'mJl1Q2dJyvX9iwz', 'HV4O4TNJbY');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Catlaina Pegram', '1307512414', 'cpegram5@abc.net.au', 'Staff', 'rJc5nUvDpL6gKxh', 'OYubwrGEv');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Lilly Brundrett', '5744761124', 'lbrundrett6@wsj.com', 'Staff', 'rKf2yGzVhP5sN7c', 'JCnPmstc');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Christophorus Fredi', '9817833023', 'cfredi7@mozilla.org', 'Staff', 'mJl1Q2dJyvX9iwz', 'dXeorR');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Weber Lavers', '7087790373', 'wlavers9@vistaprint.com', 'Staff', 'rKf2yGzVhP5sN7c', '7jpdxpT');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Cordy Caseley', '9029652149', 'ccaseleya@gravatar.com', 'Staff', 'rJc5nUvDpL6gKxh', 'SriP8cx');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Patrizia Sanper', '3397792906', 'psanperb@acquirethisname.com', 'Merchant', 'rKf2yGzVhP5sN7c', 'bUrmjz8');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Griffie Savage', '1114671145', 'gsavagec@g.co', 'Staff', 'rKf2yGzVhP5sN7c', 'R8G44E');
insert into login (fullname, phone_number, email_address, account_type, password) values ('Cassaundra Kyffin', '3057651658', 'ckyffind@go.com', 'Merchant', 'GRUr0FU');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Egan Addicott', '6373488293', 'eaddicotte@google.pl', 'Staff', 'rJc5nUvDpL6gKxh', 'LYdO68');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Calley Costock', '7165317708', 'ccostockf@g.co', 'Staff', 'rKf2yGzVhP5sN7c', 'eEZiCTjsL');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Ibbie O''Fihillie', '4968521210', 'iofihillieg@ibm.com', 'Staff', 'mJl1Q2dJyvX9iwz', 'C5GqSro5');
insert into login (fullname, phone_number, email_address, account_type, password) values ('Agustin Alibone', '1147708866', 'aaliboneh@princeton.edu', 'Merchant', 'kHOyWI6ceB');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Sigismond Thebes', '6396097632', 'sthebesi@acquirethisname.com', 'Staff', 'rKf2yGzVhP5sN7c', 'th3pbks');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Vyky Hourihane', '9852846442', 'vhourihanej@a8.net', 'Staff', 'rJc5nUvDpL6gKxh', 'exmkyxw');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Daniel Bidder', '4003796101', 'dbidderk@hhs.gov', 'Staff', 'mJl1Q2dJyvX9iwz', '6O2KYkOW');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Esra Agnolo', '6068954965', 'eagnolol@storify.com', 'Logistics', 'rKf2yGzVhP5sN7c', 'joFtOJ');
insert into login (fullname, phone_number, email_address, account_type, company_id, password) values ('Netty Oakly', '5143052104', 'noaklym@slideshare.net', 'Staff', 'rJc5nUvDpL6gKxh', 'b0iJVgp');
insert into login (fullname, phone_number, email_address, account_type, password) values ('Roselia Bett', '8902928930', 'rbettn@godaddy.com', 'Merchant', 'uW8BT1IJHtvH');
